stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-todo-app:latest .
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "Testing ......"
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - docker image tag node-todo-app:latest $DOCKERHUB_USER/node-todo-app:latest
    - docker push $DOCKERHUB_USER/node-todo-app:latest
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker-compose up -d
  tags:
    - dev
